export const COLOR = {
  // Colores generales.
  FONDO: "#FFFFFF",
  FONDO_OPACO: "#0000000b",
  FONDO_OPACO2: "#00000020",
  TEXTO_PRINCIPAL: "#292526",
  TEXTO_SECUNDARIO: "#a9a9a9",
  AZUL_PRIMARIO: "#0F67FE",
  AZUL_SECUNDARIO: "#2768d8d0",

  // Botones
  BOTON_PRIMARIO: "#0F67FE",
  BOTON_SECUNDARIO: "transparent",
  BOTON_DESTRUCTIVO: "#292526",
  TEXTO_BOTON_PRIMARIO: "#FFFFFF",
  TEXTO_BOTON_SECUNDARIO: "#292526",
  TEXTO_BOTON_DESTRUCTIVO: "#FFFFFF",
  BOTON_TAB_NAVEGACION_BIG: "#f0f0f0",

  // Extras
  SIN_COLOR: "transparent",
  BLANCO_TRANSPARENTE: "#ffffff15",
  FILTER_INFORMATION_BOX: "#ffffffbe",
  SUCCESS: "#0bb52b",
  WARNING: "#ed8309",
  ERROR: "#d90d0d",
  MORADO: "#4d008b",
  GRIS: "#dedede",
  TEXTO_TENUE: "#6B6B6B",
};
